# GATE_RUNTIME_API_VERSION reflects the contract between Go and C.
# GATE_INTERNAL_API_VERSION reflects the contracts between container, executor
# and loader binaries.

GATE_RUNTIME_API_VERSION	:= 0
GATE_INTERNAL_API_VERSION	:= $(GATE_RUNTIME_API_VERSION).0

GATE_SANDBOX			:= 1

ifneq ($(GATE_SANDBOX),1)
GATE_INTERNAL_API_VERSION	:= $(GATE_INTERNAL_API_VERSION).nosandbox
endif

CPPFLAGS += -DGATE_RUNTIME_API_VERSION=$(GATE_RUNTIME_API_VERSION) -DGATE_INTERNAL_API_VERSION=$(GATE_INTERNAL_API_VERSION) -DGATE_SANDBOX=$(GATE_SANDBOX)
