LLVM_PREFIX	:=
LLVM_SUFFIX	:=
LLVMLINK	:= $(LLVM_PREFIX)llvm-link$(LLVM_SUFFIX)
LLVMDIS		:= $(LLVM_PREFIX)llvm-dis(LLVM_SUFFIX)
LLC		:= $(LLVM_PREFIX)llc$(LLVM_SUFFIX)
OPT		:= $(LLVM_PREFIX)opt$(LLVM_SUFFIX)
