// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/manifest/manifest.proto

package manifest

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ByteRange struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length               int64    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteRange) Reset()         { *m = ByteRange{} }
func (m *ByteRange) String() string { return proto.CompactTextString(m) }
func (*ByteRange) ProtoMessage()    {}
func (*ByteRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_manifest_a0ef3eacae60ca1d, []int{0}
}
func (m *ByteRange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ByteRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ByteRange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ByteRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteRange.Merge(dst, src)
}
func (m *ByteRange) XXX_Size() int {
	return m.Size()
}
func (m *ByteRange) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteRange.DiscardUnknown(m)
}

var xxx_messageInfo_ByteRange proto.InternalMessageInfo

type Program struct {
	InitRoutine          int32             `protobuf:"varint,1,opt,name=init_routine,json=initRoutine,proto3" json:"init_routine,omitempty"`
	TextAddr             uint64            `protobuf:"varint,2,opt,name=text_addr,json=textAddr,proto3" json:"text_addr,omitempty"`
	TextSize             uint32            `protobuf:"varint,3,opt,name=text_size,json=textSize,proto3" json:"text_size,omitempty"`
	StackUsage           uint32            `protobuf:"varint,4,opt,name=stack_usage,json=stackUsage,proto3" json:"stack_usage,omitempty"`
	GlobalsSize          uint32            `protobuf:"varint,5,opt,name=globals_size,json=globalsSize,proto3" json:"globals_size,omitempty"`
	MemoryDataSize       uint32            `protobuf:"varint,6,opt,name=memory_data_size,json=memoryDataSize,proto3" json:"memory_data_size,omitempty"`
	MemorySize           uint32            `protobuf:"varint,7,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	MemorySizeLimit      uint32            `protobuf:"varint,8,opt,name=memory_size_limit,json=memorySizeLimit,proto3" json:"memory_size_limit,omitempty"`
	ModuleSize           int64             `protobuf:"varint,9,opt,name=module_size,json=moduleSize,proto3" json:"module_size,omitempty"`
	Sections             []ByteRange       `protobuf:"bytes,10,rep,name=sections" json:"sections"`
	ServiceSection       ByteRange         `protobuf:"bytes,11,opt,name=service_section,json=serviceSection" json:"service_section"`
	IoSection            ByteRange         `protobuf:"bytes,12,opt,name=io_section,json=ioSection" json:"io_section"`
	BufferSection        ByteRange         `protobuf:"bytes,13,opt,name=buffer_section,json=bufferSection" json:"buffer_section"`
	StackSection         ByteRange         `protobuf:"bytes,14,opt,name=stack_section,json=stackSection" json:"stack_section"`
	GlobalTypes          []byte            `protobuf:"bytes,15,opt,name=global_types,json=globalTypes,proto3" json:"global_types,omitempty"`
	EntryIndexes         map[string]uint32 `protobuf:"bytes,16,rep,name=entry_indexes,json=entryIndexes" json:"entry_indexes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	EntryAddrs           map[uint32]uint32 `protobuf:"bytes,17,rep,name=entry_addrs,json=entryAddrs" json:"entry_addrs" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	CallSitesSize        uint32            `protobuf:"varint,18,opt,name=call_sites_size,json=callSitesSize,proto3" json:"call_sites_size,omitempty"`
	FuncAddrsSize        uint32            `protobuf:"varint,19,opt,name=func_addrs_size,json=funcAddrsSize,proto3" json:"func_addrs_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Program) Reset()         { *m = Program{} }
func (m *Program) String() string { return proto.CompactTextString(m) }
func (*Program) ProtoMessage()    {}
func (*Program) Descriptor() ([]byte, []int) {
	return fileDescriptor_manifest_a0ef3eacae60ca1d, []int{1}
}
func (m *Program) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Program) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Program.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Program) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Program.Merge(dst, src)
}
func (m *Program) XXX_Size() int {
	return m.Size()
}
func (m *Program) XXX_DiscardUnknown() {
	xxx_messageInfo_Program.DiscardUnknown(m)
}

var xxx_messageInfo_Program proto.InternalMessageInfo

type Instance struct {
	InitRoutine          int32    `protobuf:"varint,1,opt,name=init_routine,json=initRoutine,proto3" json:"init_routine,omitempty"`
	TextAddr             uint64   `protobuf:"varint,2,opt,name=text_addr,json=textAddr,proto3" json:"text_addr,omitempty"`
	StackSize            uint32   `protobuf:"varint,3,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	StackUsage           uint32   `protobuf:"varint,4,opt,name=stack_usage,json=stackUsage,proto3" json:"stack_usage,omitempty"`
	GlobalsSize          uint32   `protobuf:"varint,5,opt,name=globals_size,json=globalsSize,proto3" json:"globals_size,omitempty"`
	MemorySize           uint32   `protobuf:"varint,6,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	MaxMemorySize        uint32   `protobuf:"varint,7,opt,name=max_memory_size,json=maxMemorySize,proto3" json:"max_memory_size,omitempty"`
	EntryIndex           uint32   `protobuf:"varint,8,opt,name=entry_index,json=entryIndex,proto3" json:"entry_index,omitempty"`
	EntryAddr            uint32   `protobuf:"varint,9,opt,name=entry_addr,json=entryAddr,proto3" json:"entry_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_manifest_a0ef3eacae60ca1d, []int{2}
}
func (m *Instance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(dst, src)
}
func (m *Instance) XXX_Size() int {
	return m.Size()
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ByteRange)(nil), "manifest.ByteRange")
	proto.RegisterType((*Program)(nil), "manifest.Program")
	proto.RegisterMapType((map[uint32]uint32)(nil), "manifest.Program.EntryAddrsEntry")
	proto.RegisterMapType((map[string]uint32)(nil), "manifest.Program.EntryIndexesEntry")
	proto.RegisterType((*Instance)(nil), "manifest.Instance")
}
func (m *ByteRange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ByteRange) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Offset != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.Offset))
	}
	if m.Length != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.Length))
	}
	return i, nil
}

func (m *Program) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Program) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.InitRoutine != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.InitRoutine))
	}
	if m.TextAddr != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.TextAddr))
	}
	if m.TextSize != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.TextSize))
	}
	if m.StackUsage != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.StackUsage))
	}
	if m.GlobalsSize != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.GlobalsSize))
	}
	if m.MemoryDataSize != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.MemoryDataSize))
	}
	if m.MemorySize != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.MemorySize))
	}
	if m.MemorySizeLimit != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.MemorySizeLimit))
	}
	if m.ModuleSize != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.ModuleSize))
	}
	if len(m.Sections) > 0 {
		for _, msg := range m.Sections {
			dAtA[i] = 0x52
			i++
			i = encodeVarintManifest(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x5a
	i++
	i = encodeVarintManifest(dAtA, i, uint64(m.ServiceSection.Size()))
	n1, err := m.ServiceSection.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x62
	i++
	i = encodeVarintManifest(dAtA, i, uint64(m.IoSection.Size()))
	n2, err := m.IoSection.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x6a
	i++
	i = encodeVarintManifest(dAtA, i, uint64(m.BufferSection.Size()))
	n3, err := m.BufferSection.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	dAtA[i] = 0x72
	i++
	i = encodeVarintManifest(dAtA, i, uint64(m.StackSection.Size()))
	n4, err := m.StackSection.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if len(m.GlobalTypes) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintManifest(dAtA, i, uint64(len(m.GlobalTypes)))
		i += copy(dAtA[i:], m.GlobalTypes)
	}
	if len(m.EntryIndexes) > 0 {
		for k, _ := range m.EntryIndexes {
			dAtA[i] = 0x82
			i++
			dAtA[i] = 0x1
			i++
			v := m.EntryIndexes[k]
			mapSize := 1 + len(k) + sovManifest(uint64(len(k))) + 1 + sovManifest(uint64(v))
			i = encodeVarintManifest(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintManifest(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x10
			i++
			i = encodeVarintManifest(dAtA, i, uint64(v))
		}
	}
	if len(m.EntryAddrs) > 0 {
		for k, _ := range m.EntryAddrs {
			dAtA[i] = 0x8a
			i++
			dAtA[i] = 0x1
			i++
			v := m.EntryAddrs[k]
			mapSize := 1 + sovManifest(uint64(k)) + 1 + sovManifest(uint64(v))
			i = encodeVarintManifest(dAtA, i, uint64(mapSize))
			dAtA[i] = 0x8
			i++
			i = encodeVarintManifest(dAtA, i, uint64(k))
			dAtA[i] = 0x10
			i++
			i = encodeVarintManifest(dAtA, i, uint64(v))
		}
	}
	if m.CallSitesSize != 0 {
		dAtA[i] = 0x90
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.CallSitesSize))
	}
	if m.FuncAddrsSize != 0 {
		dAtA[i] = 0x98
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.FuncAddrsSize))
	}
	return i, nil
}

func (m *Instance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Instance) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.InitRoutine != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.InitRoutine))
	}
	if m.TextAddr != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.TextAddr))
	}
	if m.StackSize != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.StackSize))
	}
	if m.StackUsage != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.StackUsage))
	}
	if m.GlobalsSize != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.GlobalsSize))
	}
	if m.MemorySize != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.MemorySize))
	}
	if m.MaxMemorySize != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.MaxMemorySize))
	}
	if m.EntryIndex != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.EntryIndex))
	}
	if m.EntryAddr != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintManifest(dAtA, i, uint64(m.EntryAddr))
	}
	return i, nil
}

func encodeVarintManifest(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ByteRange) Size() (n int) {
	var l int
	_ = l
	if m.Offset != 0 {
		n += 1 + sovManifest(uint64(m.Offset))
	}
	if m.Length != 0 {
		n += 1 + sovManifest(uint64(m.Length))
	}
	return n
}

func (m *Program) Size() (n int) {
	var l int
	_ = l
	if m.InitRoutine != 0 {
		n += 1 + sovManifest(uint64(m.InitRoutine))
	}
	if m.TextAddr != 0 {
		n += 1 + sovManifest(uint64(m.TextAddr))
	}
	if m.TextSize != 0 {
		n += 1 + sovManifest(uint64(m.TextSize))
	}
	if m.StackUsage != 0 {
		n += 1 + sovManifest(uint64(m.StackUsage))
	}
	if m.GlobalsSize != 0 {
		n += 1 + sovManifest(uint64(m.GlobalsSize))
	}
	if m.MemoryDataSize != 0 {
		n += 1 + sovManifest(uint64(m.MemoryDataSize))
	}
	if m.MemorySize != 0 {
		n += 1 + sovManifest(uint64(m.MemorySize))
	}
	if m.MemorySizeLimit != 0 {
		n += 1 + sovManifest(uint64(m.MemorySizeLimit))
	}
	if m.ModuleSize != 0 {
		n += 1 + sovManifest(uint64(m.ModuleSize))
	}
	if len(m.Sections) > 0 {
		for _, e := range m.Sections {
			l = e.Size()
			n += 1 + l + sovManifest(uint64(l))
		}
	}
	l = m.ServiceSection.Size()
	n += 1 + l + sovManifest(uint64(l))
	l = m.IoSection.Size()
	n += 1 + l + sovManifest(uint64(l))
	l = m.BufferSection.Size()
	n += 1 + l + sovManifest(uint64(l))
	l = m.StackSection.Size()
	n += 1 + l + sovManifest(uint64(l))
	l = len(m.GlobalTypes)
	if l > 0 {
		n += 1 + l + sovManifest(uint64(l))
	}
	if len(m.EntryIndexes) > 0 {
		for k, v := range m.EntryIndexes {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovManifest(uint64(len(k))) + 1 + sovManifest(uint64(v))
			n += mapEntrySize + 2 + sovManifest(uint64(mapEntrySize))
		}
	}
	if len(m.EntryAddrs) > 0 {
		for k, v := range m.EntryAddrs {
			_ = k
			_ = v
			mapEntrySize := 1 + sovManifest(uint64(k)) + 1 + sovManifest(uint64(v))
			n += mapEntrySize + 2 + sovManifest(uint64(mapEntrySize))
		}
	}
	if m.CallSitesSize != 0 {
		n += 2 + sovManifest(uint64(m.CallSitesSize))
	}
	if m.FuncAddrsSize != 0 {
		n += 2 + sovManifest(uint64(m.FuncAddrsSize))
	}
	return n
}

func (m *Instance) Size() (n int) {
	var l int
	_ = l
	if m.InitRoutine != 0 {
		n += 1 + sovManifest(uint64(m.InitRoutine))
	}
	if m.TextAddr != 0 {
		n += 1 + sovManifest(uint64(m.TextAddr))
	}
	if m.StackSize != 0 {
		n += 1 + sovManifest(uint64(m.StackSize))
	}
	if m.StackUsage != 0 {
		n += 1 + sovManifest(uint64(m.StackUsage))
	}
	if m.GlobalsSize != 0 {
		n += 1 + sovManifest(uint64(m.GlobalsSize))
	}
	if m.MemorySize != 0 {
		n += 1 + sovManifest(uint64(m.MemorySize))
	}
	if m.MaxMemorySize != 0 {
		n += 1 + sovManifest(uint64(m.MaxMemorySize))
	}
	if m.EntryIndex != 0 {
		n += 1 + sovManifest(uint64(m.EntryIndex))
	}
	if m.EntryAddr != 0 {
		n += 1 + sovManifest(uint64(m.EntryAddr))
	}
	return n
}

func sovManifest(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozManifest(x uint64) (n int) {
	return sovManifest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ByteRange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManifest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ByteRange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ByteRange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipManifest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthManifest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Program) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManifest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Program: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Program: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitRoutine", wireType)
			}
			m.InitRoutine = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitRoutine |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TextAddr", wireType)
			}
			m.TextAddr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TextAddr |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TextSize", wireType)
			}
			m.TextSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TextSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StackUsage", wireType)
			}
			m.StackUsage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StackUsage |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalsSize", wireType)
			}
			m.GlobalsSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GlobalsSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryDataSize", wireType)
			}
			m.MemoryDataSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryDataSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemorySize", wireType)
			}
			m.MemorySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemorySize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemorySizeLimit", wireType)
			}
			m.MemorySizeLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemorySizeLimit |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleSize", wireType)
			}
			m.ModuleSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModuleSize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sections = append(m.Sections, ByteRange{})
			if err := m.Sections[len(m.Sections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ServiceSection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IoSection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IoSection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferSection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferSection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StackSection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StackSection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalTypes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalTypes = append(m.GlobalTypes[:0], dAtA[iNdEx:postIndex]...)
			if m.GlobalTypes == nil {
				m.GlobalTypes = []byte{}
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryIndexes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EntryIndexes == nil {
				m.EntryIndexes = make(map[string]uint32)
			}
			var mapkey string
			var mapvalue uint32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowManifest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowManifest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthManifest
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowManifest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipManifest(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthManifest
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.EntryIndexes[mapkey] = mapvalue
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryAddrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManifest
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EntryAddrs == nil {
				m.EntryAddrs = make(map[uint32]uint32)
			}
			var mapkey uint32
			var mapvalue uint32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowManifest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowManifest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowManifest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipManifest(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthManifest
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.EntryAddrs[mapkey] = mapvalue
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallSitesSize", wireType)
			}
			m.CallSitesSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallSitesSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FuncAddrsSize", wireType)
			}
			m.FuncAddrsSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FuncAddrsSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipManifest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthManifest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Instance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManifest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Instance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Instance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitRoutine", wireType)
			}
			m.InitRoutine = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitRoutine |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TextAddr", wireType)
			}
			m.TextAddr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TextAddr |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StackSize", wireType)
			}
			m.StackSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StackSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StackUsage", wireType)
			}
			m.StackUsage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StackUsage |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalsSize", wireType)
			}
			m.GlobalsSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GlobalsSize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemorySize", wireType)
			}
			m.MemorySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemorySize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMemorySize", wireType)
			}
			m.MaxMemorySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMemorySize |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryIndex", wireType)
			}
			m.EntryIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntryIndex |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryAddr", wireType)
			}
			m.EntryAddr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EntryAddr |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipManifest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthManifest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipManifest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowManifest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowManifest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthManifest
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowManifest
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipManifest(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthManifest = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowManifest   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("internal/manifest/manifest.proto", fileDescriptor_manifest_a0ef3eacae60ca1d)
}

var fileDescriptor_manifest_a0ef3eacae60ca1d = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xee, 0x36, 0x6d, 0x9a, 0x3d, 0xc9, 0x66, 0xdb, 0x69, 0x91, 0xa5, 0x62, 0x9a, 0x56, 0x28,
	0xc1, 0x8b, 0x0a, 0x8a, 0x50, 0x14, 0xff, 0x82, 0x82, 0x05, 0x15, 0xd9, 0xea, 0xf5, 0x32, 0xcd,
	0x9e, 0xc4, 0xa1, 0xbb, 0xb3, 0x65, 0x67, 0x52, 0x92, 0x3e, 0x80, 0xd7, 0x3e, 0x8d, 0xcf, 0xd0,
	0x4b, 0x9f, 0x40, 0xb4, 0xbe, 0x88, 0xcc, 0x99, 0xdd, 0x4d, 0x6d, 0xd1, 0x5c, 0xe8, 0xdd, 0xcc,
	0x37, 0xdf, 0xf7, 0x9d, 0x64, 0xcf, 0x77, 0x0e, 0x74, 0x85, 0xd4, 0x98, 0x4b, 0x9e, 0xdc, 0x4d,
	0xb9, 0x14, 0x43, 0x54, 0xba, 0x3a, 0xec, 0x9d, 0xe4, 0x99, 0xce, 0x58, 0xa3, 0xbc, 0xef, 0x3c,
	0x02, 0xb7, 0x3f, 0xd5, 0x18, 0x72, 0x39, 0x42, 0x76, 0x03, 0xea, 0xd9, 0x70, 0xa8, 0x50, 0x07,
	0x4e, 0xd7, 0xe9, 0xd5, 0xc2, 0xe2, 0x66, 0xf0, 0x04, 0xe5, 0x48, 0x7f, 0x0c, 0x16, 0x2d, 0x6e,
	0x6f, 0x3b, 0x9f, 0x1a, 0xb0, 0xf2, 0x2e, 0xcf, 0x46, 0x39, 0x4f, 0xd9, 0x36, 0xb4, 0x84, 0x14,
	0x3a, 0xca, 0xb3, 0xb1, 0x16, 0x12, 0xc9, 0x61, 0x39, 0x6c, 0x1a, 0x2c, 0xb4, 0x10, 0xbb, 0x09,
	0xae, 0xc6, 0x89, 0x8e, 0x78, 0x1c, 0xe7, 0xe4, 0xb4, 0x14, 0x36, 0x0c, 0xf0, 0x3c, 0x8e, 0xf3,
	0xea, 0x51, 0x89, 0x33, 0x0c, 0x6a, 0x5d, 0xa7, 0xe7, 0xd9, 0xc7, 0x43, 0x71, 0x86, 0x6c, 0x0b,
	0x9a, 0x4a, 0xf3, 0xc1, 0x71, 0x34, 0x56, 0x7c, 0x84, 0xc1, 0x12, 0x3d, 0x03, 0x41, 0x1f, 0x0c,
	0x62, 0xaa, 0x8f, 0x92, 0xec, 0x88, 0x27, 0xca, 0x1a, 0x2c, 0x13, 0xa3, 0x59, 0x60, 0xe4, 0xd1,
	0x83, 0xd5, 0x14, 0xd3, 0x2c, 0x9f, 0x46, 0x31, 0xd7, 0xdc, 0xd2, 0xea, 0x44, 0x6b, 0x5b, 0xfc,
	0x05, 0xd7, 0xbc, 0xac, 0x56, 0x30, 0x89, 0xb4, 0x62, 0xab, 0x59, 0x88, 0x08, 0x77, 0x60, 0xed,
	0x12, 0x21, 0x4a, 0x44, 0x2a, 0x74, 0xd0, 0x20, 0x9a, 0x3f, 0xa3, 0xbd, 0x36, 0x30, 0x99, 0x65,
	0xf1, 0x38, 0x41, 0x6b, 0xe6, 0xd2, 0x07, 0x04, 0x0b, 0x91, 0xd9, 0x03, 0x68, 0x28, 0x1c, 0x68,
	0x91, 0x49, 0x15, 0x40, 0xb7, 0xd6, 0x6b, 0xde, 0x5b, 0xdf, 0xab, 0xda, 0x55, 0xf5, 0xa6, 0xbf,
	0x74, 0xfe, 0x6d, 0x6b, 0x21, 0xac, 0xa8, 0xac, 0x0f, 0xbe, 0xc2, 0xfc, 0x54, 0x0c, 0x30, 0x2a,
	0xb0, 0xa0, 0xd9, 0x75, 0xfe, 0xae, 0x6e, 0x17, 0x8a, 0x43, 0x2b, 0x60, 0xfb, 0x00, 0x22, 0xab,
	0xe4, 0xad, 0x79, 0x72, 0x57, 0x64, 0xa5, 0xf2, 0x19, 0xb4, 0x8f, 0xc6, 0xc3, 0x21, 0xe6, 0x95,
	0xda, 0x9b, 0xa7, 0xf6, 0xac, 0xa0, 0x74, 0x78, 0x02, 0x9e, 0x6d, 0x69, 0x69, 0xd0, 0x9e, 0x67,
	0xd0, 0x22, 0x7e, 0xa9, 0xaf, 0x3a, 0x1e, 0xe9, 0xe9, 0x09, 0xaa, 0xc0, 0xef, 0x3a, 0xbd, 0x56,
	0xd9, 0xf1, 0xf7, 0x06, 0x62, 0x6f, 0xc1, 0x43, 0xa9, 0xf3, 0x69, 0x24, 0x64, 0x8c, 0x13, 0x54,
	0xc1, 0x2a, 0x7d, 0xde, 0xdb, 0xb3, 0x12, 0x45, 0x78, 0xf7, 0x5e, 0x1a, 0xda, 0x81, 0x65, 0xd1,
	0xb9, 0x2c, 0x89, 0x97, 0x1e, 0xd8, 0x2b, 0x68, 0x5a, 0x3f, 0x13, 0x60, 0x15, 0xac, 0x91, 0xdb,
	0xf6, 0x1f, 0xdc, 0x4c, 0xa8, 0x7f, 0xf3, 0x02, 0xac, 0x60, 0xb6, 0x0b, 0xfe, 0x80, 0x27, 0x49,
	0xa4, 0x84, 0xc6, 0x22, 0xb1, 0x8c, 0xe2, 0xe3, 0x19, 0xf8, 0xd0, 0xa0, 0x94, 0x8d, 0x5d, 0xf0,
	0x87, 0x63, 0x39, 0xb0, 0x05, 0x2d, 0x6f, 0xdd, 0xf2, 0x0c, 0x4c, 0x5e, 0x86, 0xb7, 0xf9, 0x14,
	0xd6, 0xae, 0xfd, 0x05, 0xb6, 0x0a, 0xb5, 0x63, 0x9c, 0xd2, 0x20, 0xba, 0xa1, 0x39, 0xb2, 0x0d,
	0x58, 0x3e, 0xe5, 0xc9, 0x18, 0x69, 0xf8, 0xbc, 0xd0, 0x5e, 0x1e, 0x2e, 0xee, 0x3b, 0x9b, 0x8f,
	0xc1, 0xbf, 0xf2, 0xab, 0x2f, 0xcb, 0xbd, 0x39, 0xf2, 0x9d, 0x2f, 0x8b, 0xd0, 0x38, 0x90, 0x4a,
	0x73, 0x39, 0xc0, 0x7f, 0xde, 0x04, 0xb7, 0x00, 0x8a, 0x64, 0xcc, 0x56, 0x81, 0x6b, 0x7b, 0xff,
	0xbf, 0x76, 0xc1, 0x95, 0x09, 0xaf, 0x5f, 0x9b, 0xf0, 0x5d, 0xf0, 0x53, 0x3e, 0x89, 0xae, 0xaf,
	0x01, 0x2f, 0xe5, 0x93, 0x37, 0x33, 0xde, 0x56, 0x19, 0x09, 0x8a, 0x58, 0xb1, 0x03, 0x60, 0x96,
	0x1a, 0xf3, 0x67, 0x66, 0x99, 0xa1, 0xe9, 0xf7, 0x42, 0xb7, 0x4a, 0x42, 0x7f, 0xe3, 0xfc, 0x47,
	0x67, 0xe1, 0xfc, 0xa2, 0xe3, 0x7c, 0xbd, 0xe8, 0x38, 0xdf, 0x2f, 0x3a, 0xce, 0xe7, 0x9f, 0x9d,
	0x85, 0xa3, 0x3a, 0x6d, 0xe9, 0xfb, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x88, 0xcd, 0xf4, 0x49,
	0xc9, 0x05, 0x00, 0x00,
}
