GATEDIR		:= ../..

LIBS := \
	$(GATEDIR)/libc/compat.bc \
	$(GATEDIR)/libc/libc_build/memcpy.bc \
	$(GATEDIR)/libc/libc_build/memset.bc \
	$(GATEDIR)/libc/libc_build/strlen.bc \
	$(GATEDIR)/malloc/malloc.bc \
	$(GATEDIR)/malloc/morecore.bc \
	$(GATEDIR)/malloc/wasm.bc

include $(GATEDIR)/tests/test.mk
